/**
 * Regenerates data/sample.js from data/vendor-master.csv.
 *
 * The CSV is the source of truth (the tests read it, and visitors can download
 * it). Embedding a copy as JavaScript means the demo also works when the page
 * is opened straight off disk, with no fetch and no server.
 *
 * Run after editing the CSV:  node tools/build-sample.js
 */
var fs = require('fs');
var path = require('path');

var csvPath = path.join(__dirname, '..', 'data', 'vendor-master.csv');
var outPath = path.join(__dirname, '..', 'data', 'sample.js');

var csv = fs.readFileSync(csvPath, 'utf8');
var out =
  '/* Generated by tools/build-sample.js — do not edit by hand.\n' +
  '   Source: data/vendor-master.csv */\n' +
  'window.CLEANROOM_SAMPLE = ' + JSON.stringify(csv) + ';\n';

fs.writeFileSync(outPath, out, 'utf8');

var lines = csv.trim().split('\n').length - 1;
console.log('Wrote data/sample.js — ' + lines + ' records, ' + out.length + ' bytes.');
